Use the conditions below and the news items in the DOCUMENTS section to answer the questions in the QUESTION section.
Conditions :
1. find the news data in the DOCUMENTS item according to the QUESTION.
2. if the content exists, translate the title and content into Korean and output it in the following form. There may be multiple cases.
    News title: {{title}}
    Summary content: {{content}}
    Link to the article: {{Link}}
3. If there is no content for QUESTION, output the following sentence.
There is no relevant news.

QUESTION :
{input}


DOCUMENTS:
{documents}